#! /bin/bash

function divide()
{
	a="$1"
	b="$2"
	res=0
	ret_status=0
	
	if [[ $b -eq 0 ]]; then
		ret_status=1
	else
		(( res = $a / $b ))
		echo "$res"
	fi
	return $ret_status
}

function main()
{
	echo "$(divide $1 $2)"
}

main "$1" "$2"
