#! /bin/bash


function is_prime()
{
num=$1
i=2
result=true
 
	if [[ $num -lt 2 ]]; then
	    result=false
	else    
	
	    while [[ "$i" -lt "$num" ]]; do
	        if (( $num % $i == 0 )); then
	            result=false
                break
	        fi
	        (( i=$i + 1 ))
        done	    
    fi


    echo $result
	return 0   
}



function main()
{
	result="$(is_prime $1)"
	ret_status=$?
	
	if [[ "$ret_status" -eq 0 ]]; then
		echo "$result"
	else
		echo "Error in function 'is_prime'"
	fi
	
	return $ret_status
}



main $1 

